version: '2'
services:


  facilemanager:
    image: micahmitchell/facilemanager:latest
    hostname: ${fm_URL}
    container_name: ${COMPOSE_PROJECT_NAME}-web
    networks:
      - frontend
      - backend
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
#    ports:
#      - 80:80
    stop_grace_period: 1m
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_HOST: "${COMPOSE_PROJECT_NAME}-db"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: ${COMPOSE_PROJECT_NAME}-db
    networks:
      - backend
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./mysql-data:/var/lib/mysql
    #ports:
    #  - 3306:3306
    stop_grace_period: 1m
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"


  fmdns:
    image: micahmitchell/fmdns:latest
    hostname: ${fmDNS_URL}
    container_name: ${COMPOSE_PROJECT_NAME}-bind9
    networks:
      - frontend
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./fmdns-log:/var/log/bind
    ports:
      - ${fmDNS_External_IP}:53:53/udp
      - ${fmDNS_External_IP}:53:53/tcp
    #  - 80:80
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      FACILE_MANAGER_HOST: ${fmDNS_Manager}
      FACILE_CLIENT_SERIAL_NUMBER: ${fmDNS_Serial}
      FACILE_CLIENT_URL: ${fmDNS_URL}

#volumes:
#    mysql:

networks:
    frontend:
        external: true
    backend:
